---
- name: download couchdb
  shell: curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | sudo apt-key add -

- name: download couchdb
  shell: echo "deb https://apache.bintray.com/couchdb-deb bionic main" | sudo tee -a /etc/apt/sources.list

- name: install couchdb
  apt:
    name: couchdb
    update_cache: yes
    state: present

- name: install python-couchdb
  command: pip3 install couchdb

- name: add right to write .ini file
  command: chmod 777 /opt/couchdb/etc/local.ini

- name: Edit the local.ini
  lineinfile:
    path: /opt/couchdb/etc/local.ini
    line: '{{ item }}'
    state: present
  with_items:
    - "[chttpd]"
    - "bind_address = 0.0.0.0"
    - "[admins]"
    - "admin = password"

- name: add right to write vm.args file
  command: chmod 777 /opt/couchdb/etc/vm.args

- name: Edit the configuration fil
  lineinfile:
    path: /opt/couchdb/etc/vm.args
    line: "-name couchdb@ {{ master_IP }}"
    state: present


- name: add right to write sys.config file
  command: chmod 777 /opt/couchdb/releases/2.3.1/sys.config

- name: Edit the sys.config
  lineinfile:
    path: /opt/couchdb/releases/2.3.1/sys.config
    line: '{{ item }}'
    state: present
  with_items:
    - "["
    - "    {lager, ["
    - "        {error_logger_hwm, 1000},"
    - "        {error_logger_redirect, true},"
    - "        {handlers, ["
    - "            {lager_console_backend, [debug, {"
    - "                lager_default_formatter,"
    - "                ["
    - "                    date, \" \", time,"
    - "                    \" [\", severity, \"] \","
    - "                    node, \" \", pid, \" \","
    - "                    message,"
    - "                    \"\n\""
    - "                ]"
    - "            }]}"
    - "        ]},"
    - "        {inet_dist_listen_min, 9100},"
    - "        {inet_dist_listen_max, 9200}"
    - "    ]}"
    - "]."




