---
- name: pull an couchdb image
  docker_image:
    name: couchdb:2.3.0

- name: create couch db container
  docker_container: 
    name: couchdb 
    image: couchdb
    restart: yes
    ports: 
      - "5984:5984/tcp" 




# - name: configure cookie in docker container
#   command: sudo docker exec -it couchdb bash -c "echo \"-setcookie couchdb_cluster\" >> /opt/couchdb/etc/vm.args"

- name: configure hostname in docker container
  command: docker exec -it couchdb bash -c "echo \"-name couchdb@{{ ansible_eth0.ipv4.address }}\" >> /opt/couchdb/etc/vm.args"

- name: configure hostname in docker container
  command: docker exec -it couchdb bash -c "echo \"-kernel inet_dist_listen_max 9200\" >> /opt/couchdb/etc/vm.args"

# - name: restart docker container
#   docker_container:
#     name: mycouchdb
#     restart: yes

# - name: make a directory
#   file: 
#     path: /home/ubuntu/ngrok
#     state: directory

# - name: wget ngrok
#   get_url:
#     url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
#     dest: /home/ubuntu/ngrok

# - name: install unzip
#   apt: name=unzip state=present

# - name: unzip ngrok
#   unarchive:
#     src: /home/ubuntu/ngrok/ngrok-stable-linux-amd64.zip
#     dest: /home/ubuntu/ngrok
#     remote_src: yes
#     creates: /home/ubuntu/ngrok/ngrok

# # - name: mount http 5984
#   command: /home/ubuntu/ngrok/ngrok http 5984