---
# - name: install web structure 
#   apt:
#     name: "{{ web_structure }}"
#     update_cache: yes
#     state: latest

- name: install python
  apt:
    name: python
    update_cache: yes
    state: present

- name: install pip
  apt:
    name: python-pip
    state: latest

- name: install openstacksdk
  pip:
    name: openstacksdk
    state: latest
