---
- name: install all essential tools 
  apt:
    name: "{{ essential_tools }}"
    update_cache: yes
    state: present
    
- name: install tweepy
  command: pip3 install tweepy

- name: install Shapely
  command: pip3 install Shapely

- name: install nltk
  command: pip3 install nltk

