---
# - name: install web structure 
#   apt:
#     name: "{{ web_structure }}"
#     update_cache: yes
#     state: latest

- name: install python3
  apt:
    name: python3
    update_cache: yes
    state: present

- name: install pip3
  apt:
    name: python3-pip
    state: latest

- name: install pip
  apt:
    name: python-pip
    state: latest

- name: install vim
  apt:
    name: vim
    state: latest

- name: install erlang-base
  apt:
    name: erlang-base-hipe
    state: latest

- name: install nltk
  pip:
    name: nltk