---
- hosts: slave3
  remote_user: ubuntu
  become: yes
  
  tasks:
    - name: make a directory
      file: 
        path: /mnt/data/harvester
        state: absent

    - name: make a directory
      file: 
        path: /mnt/data/harvester
        state: directory

    - name: "Copy Hosts file to Servers"
      copy:
        src: ../harvester.zip
        dest: /mnt/data/harvester/harvester.zip
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: unzip
      unarchive:
        src: /mnt/data/harvester/harvester.zip
        dest: /mnt/data/harvester
        remote_src: yes
        creates: /mnt/data/harvester/harvester

    # - name: run harvester
    #   shell: nohup python3 Main_Harvester.py LzOxVuyHgGu9QP4b8skZxUVvS nbLuOAibNpCiiLfgsMwKTPiV4PYNhTK21ddWli40T3dI08YgY4 1120218841278115840-6CgqMItD1yLdo1ejbnhfgNfIBz5upA TqcBGcTzgNKkkLipAw3wmHek8iTg8bM7vwirfL7wYT23t 5000 20000 &
    #   args:
    #     chdir: /mnt/data/harvester/harvester
    # - name: run harvester
    #   shell: nohup python3 Main_Harvester.py ixowvyfcvBUrJ5EvEjBknxFDb RCJyd2ufW3aWZLykF1FOvsqC4q3gJIeeF5D7aHaqILrSc3MaZx 1127792942859423744-bAHDjdmgAkyd85ci56cI8cqhLTCIPo U6N2IvWrFW8T2LvEiKPziEpCVtO86wKgQtzFNx8d8n6aw 10000 20000 &
    #   args:
    #     chdir: /mnt/data/harvester/harvester
    # - name: run harvester
    #   shell: nohup python3 Main_Harvester.py qNM0Oq97DR3VcX7prwVTzvfog nXxUSJKGI9G3vNw7SU5vkB4JYvrqTNgs0Y96nQdSBi1tByMeF4 1127796807260459008-EnIm1VJhsOirsdcr7ahaTelMjqLujr GHzni3rwi0YtBAyJFgSV0Q6IwhQuR92zO1T8WlqGnDfiO 15000 20000 &
    #   args:
    #     chdir: /mnt/data/harvester/harvester
    - name: run harvester
      shell: nohup python3 Main_Harvester.py fF3Ga382lSPnu8S35q3al9R8t OocybjkiOs5l32YgJJ7UrE5dIA7IgPp29So5pIzztCpFLvLz08 1127799065117216768-9W8FOQD4VGP1tofGtvTjfi9GhtAP8e felNrM5rfj0REI3ArkM8T5wMV5s9TEAIFL0DTpkPQ69nw 20000 20000 &
      args:
        chdir: /mnt/data/harvester/harvester




    # - name: run tweets listen
    #   shell: nohup python3 Main_Listen.py LzOxVuyHgGu9QP4b8skZxUVvS nbLuOAibNpCiiLfgsMwKTPiV4PYNhTK21ddWli40T3dI08YgY4 1120218841278115840-6CgqMItD1yLdo1ejbnhfgNfIBz5upA TqcBGcTzgNKkkLipAw3wmHek8iTg8bM7vwirfL7wYT23t 112.921114 -26.441329 134.0151665 -9.142176 &
    #   args:
    #     chdir: /mnt/data/harvester/harvester
    # - name: run tweets listen
    #   shell: nohup python3 Main_Listen.py ixowvyfcvBUrJ5EvEjBknxFDb RCJyd2ufW3aWZLykF1FOvsqC4q3gJIeeF5D7aHaqILrSc3MaZx 1127792942859423744-bAHDjdmgAkyd85ci56cI8cqhLTCIPo U6N2IvWrFW8T2LvEiKPziEpCVtO86wKgQtzFNx8d8n6aw 112.921114 -43.740482 134.0151665 -26.441329 &
    #   args:
    #     chdir: /mnt/data/harvester/harvester

    # - name: run tweets listen
    #   shell: nohup python3 Main_Listen.py qNM0Oq97DR3VcX7prwVTzvfog nXxUSJKGI9G3vNw7SU5vkB4JYvrqTNgs0Y96nQdSBi1tByMeF4 1127796807260459008-EnIm1VJhsOirsdcr7ahaTelMjqLujr GHzni3rwi0YtBAyJFgSV0Q6IwhQuR92zO1T8WlqGnDfiO 134.0151665 -26.441329 159.109219 -9.142176 &
    #   args:
    #     chdir: /mnt/data/harvester/harvester
    - name: run tweets listen
      shell: nohup python3 Main_Listen.py fF3Ga382lSPnu8S35q3al9R8t OocybjkiOs5l32YgJJ7UrE5dIA7IgPp29So5pIzztCpFLvLz08 1127799065117216768-9W8FOQD4VGP1tofGtvTjfi9GhtAP8e felNrM5rfj0REI3ArkM8T5wMV5s9TEAIFL0DTpkPQ69nw 134.0151665 -43.740482 159.109219 -26.441329 &
      args:
        chdir: /mnt/data/harvester/harvester





