---
- hosts: websrvs 
  remote_user: ubuntu
  become: yes
  
  tasks:
    - name: install nginx
      apt: name=nginx state=latest update_cache=yes

    - name: make a directory
      file: 
        path: /home/ubuntu/ngrok
        state: directory

    - name: add proxy discription
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        #state: absent
      with_items:
        - "http_proxy=\"http://wwwproxy.unimelb.edu.au:8000\""
        - "https_proxy=\"http://wwwproxy.unimelb.edu.au:8000\""
        - "ftp_proxy=\"http://wwwproxy.unimelb.edu.au:8000\""

    #use ngrok to set web proxy
    - name: wget ngrok
      get_url:
        url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        dest: /home/ubuntu/ngrok

    - name: install unzip
      apt: name=unzip state=present

    - name: unzip ngrok
      unarchive:
        src: /home/ubuntu/ngrok/ngrok-stable-linux-amd64.zip
        dest: /home/ubuntu/ngrok
        remote_src: yes
        creates: /home/ubuntu/ngrok/ngrok

    #- name: mount http 80
      #command: /home/ubuntu/ngrok/ngrok http 80



