#Here is the parameters for users who can change as they prefer 
#Our group run these defult paras on our own vm
#So you may need to heck by yourself that the paras you set are available on yours vm

state: present

instance:
     name1: master
     name2: slave1
     name3: slave2
     name4: slave3
     # unimelb 
     availability_zone: melbourne-qh2-uom
     # 2 cores and 9GB
     flavor: uom.mse.2c9g
     image: NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)
     # unimelb internal network
     network: qh2-uom-internal
     # the key pair you want to use to login virtual machines, make sure you already create one befor run launch.sh
     key_name: nectar
     #the path where you store the key pair 
     key_file_path: ~/.ssh/nectar.pem
     
volume:
     name1: master
     name2: slave1
     name3: slave2
     name4: slave3
     volume_size_master: 100
     volume_size_slave: 50

#used as the group name of hosts
hosts_group: myServer


web_structure: apache2
essential_tools: ['vim','python3', 'zip', 'unzip', 'curl', 'python-dev', 'python-pip', 'python3-pip', 'nodejs', 'npm', 'docker.io']


couchdb_name: mycouchdb

security_rules:
     - name: ssh
       protocol: tcp
       port_range_min: 22
       port_range_max: 22
       remote_ip_prefix: 0.0.0.0/0
     - name: http
       protocol: tcp
       port_range_min: 80
       port_range_max: 80
       remote_ip_prefix: 0.0.0.0/0
     - name: http
       protocol: tcp
       port_range_min: 443
       port_range_max: 443
       remote_ip_prefix: 0.0.0.0/0
     - name: http
       protocol: tcp
       port_range_min: 5000
       port_range_max: 5000
       remote_ip_prefix: 0.0.0.0/0
     - name: server
       protocol: tcp
       port_range_min: 5984
       port_range_max: 5984
       remote_ip_prefix: 0.0.0.0/0
     - name: server
       protocol: tcp
       port_range_min: 4369
       port_range_max: 4369
       remote_ip_prefix: 0.0.0.0/0
     - name: server
       protocol: tcp
       port_range_min: 9100
       port_range_max: 9200
       remote_ip_prefix: 0.0.0.0/0

master_IP: 172.26.37.226
slave1_IP: 172.26.37.234
slave2_IP: 172.26.38.22
slave3_IP: 172.26.37.175
