---
- name: make a directory
  file: 
    path: /mnt/data/web_server
    state: directory

- name: "Copy Hosts file to Servers"
  copy:
    src: ../front+back.zip
    dest: /mnt/data/web_server/front+back.zip
    owner: ubuntu
    group: ubuntu
    mode: 0777
    backup: yes

- name: unzip
  unarchive:
    src: /mnt/data/web_server/front+back.zip
    dest: /mnt/data/web_server
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: 0777
    backup: yes
    creates: /mnt/data/web_server/DeadlySins


- name: install web dependencies
  shell: npm install 
  become: yes
  args:
    chdir: /mnt/data/web_server/DeadlySins

- name: install "{{ item }}"
  shell: pip3 install "{{ item }}"
  with_items:
    - flask
    - flask_cors

- name: run flask
  shell: nohup python3 flaskapp.py &
  become: yes
  args:
    chdir: /mnt/data/web_server/flask/



